name = "ChargingPower"
uuid = "c13b3977-9e2a-4036-95bd-a9c8f59a277f"
authors = ["Dario Rosa <dario.rosa85@gmail.com>"]
version = "0.1.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
SparseArrays = "1.11.0"
